blog_create:
  path: /blog/create
  controller: MyBasicModule\Controller\CommentController::indexAction

blog_list:
  path: /blog/list
  controller: MyBasicModule\Controller\CommentController::listAction

blog_update:
  path: /blog/update/{id}
  controller: MyBasicModule\Controller\CommentController::updateAction

blog_delete:
  path: /blog/delete/{id}
  controller: MyBasicModule\Controller\CommentController::deleteAction